FROM frolvlad/alpine-python3:latest
ENV CLANENV=prod

RUN mkdir ./app
ADD requirements.txt /app
WORKDIR /app
RUN \
 apk add --no-cache postgresql-libs python3-dev && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
RUN apk update

ADD clan.py /app
ADD config.py /app
ADD app/ /app/app

EXPOSE 5000
cmd ["python3", "clan.py", "--debug"]