FROM frolvlad/alpine-python3:latest
ENV CLANENV=dev

RUN mkdir -p ./app/tests
ADD db.sqlite3 /app
ADD config.py /app
ADD requirements.txt /app
ADD tests/ /app/tests
ADD app/ /app/app
WORKDIR /app

RUN \
 apk add --no-cache postgresql-libs python3-dev && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps

RUN apk update

CMD ["py.test", "tests/test_destiny.py"]