FROM frolvlad/alpine-python3:latest
ENV CLANENV=dev
RUN mkdir ./app
ADD requirements.txt /app
WORKDIR /app
RUN \
 apk add --no-cache postgresql-libs python3-dev && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
RUN mkdir /etc/supervisor.d/
ADD clan.py /app
ADD config.py /app
ADD app/ /app/app
ADD redis_queue.py /app
ADD pgcr_consumer.py /app
ADD db.sqlite3 /app
ADD pgcr_collector.py /app
ADD stat_collector.py /app
ADD redis_send_player_ids_pvp.py /app
ADD redis_send_player_ids_stats.py /app
ADD supervisor.ini /etc/supervisor.d/
RUN apk update
RUN apk add --no-cache supervisor

CMD ["supervisord", "--nodaemon", "-c", "/etc/supervisord.conf"]