version: '3'
services:
  sfapi:
    build:
      context: .
      dockerfile: Dockerfile.prod.api
    container_name: sfapiprod
    networks:
      - sfprod
    extra_hosts:
      - "db:172.17.0.1"
  sffe:
    build:
      context: .
      dockerfile: Dockerfile.prod.frontend
    container_name: sffeprod
    ports:
      - "80:80"
    networks:
      - sfprod
  sfworkers:
    build:
      context: .
      dockerfile: Dockerfile.prod.workers
    container_name: sfworkersprod
    networks:
      - sfprod
    extra_hosts:
      - "db:172.17.0.1"
  redis:
    container_name: sfredisprod
    image: "redis:alpine"
    networks:
      - sfprod
networks:
  sfprod:
    driver_opts:
      com.docker.network.bridge.name: sfprod
    ipam:
      driver: default
      config:
        - subnet: "10.5.0.0/24"