version: '3'
services:
  sfapi:
    image: "sfapi-dev:${BUILD_ID}"
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev.api
  sffe:
    image: "sffe-dev:${BUILD_ID}"
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev.frontend
    ports:
      - "80:80"
  sfworkers:
    image: "sfworkers-dev:${BUILD_ID}"
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev.workers
  redis:
    image: "redis:alpine"