"""foxinit

Revision ID: 235f6a31e439
Revises: 
Create Date: 2019-03-23 16:29:53.276855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235f6a31e439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectibles_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collectible_hash', sa.String(), nullable=True),
    sa.Column('item_hash', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('presentation_node_type', sa.String(), nullable=True),
    sa.Column('parent_presentation_node_hash', sa.String(), nullable=True),
    sa.Column('expansion_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('membership_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.Column('gun_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('char_id', sa.String(), nullable=True),
    sa.Column('last_pvp_match', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectibles_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_player', sa.Integer(), nullable=True),
    sa.Column('parent_collectible', sa.Integer(), nullable=True),
    sa.Column('date_collected', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_collectible'], ['collectibles_game.id'], ),
    sa.ForeignKeyConstraint(['parent_player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_player', sa.Integer(), nullable=True),
    sa.Column('glory', sa.Integer(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapondata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_weapon', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('match_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['parent_weapon'], ['weapon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapondata')
    op.drop_table('playerstats')
    op.drop_table('collectibles_player')
    op.drop_table('character')
    op.drop_table('weapon')
    op.drop_table('player')
    op.drop_table('manifest')
    op.drop_table('collectibles_game')
    # ### end Alembic commands ###
