"""manifestupdatetime

Revision ID: 810fb64083e2
Revises: bc55cecd178a
Create Date: 2019-05-13 09:42:44.019816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810fb64083e2'
down_revision = 'bc55cecd178a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifest', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manifest', 'updated')
    # ### end Alembic commands ###
