"""rostertwo

Revision ID: b4fd86f3c4a3
Revises: 810fb64083e2
Create Date: 2019-06-10 15:16:20.348603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fd86f3c4a3'
down_revision = '810fb64083e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.add_column('player', sa.Column('last_activeity_time', sa.DateTime(), nullable=True))
    op.add_column('player', sa.Column('last_activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'last_activity')
    op.drop_column('player', 'last_activeity_time')
    op.drop_column('player', 'join_date')
    # ### end Alembic commands ###
