"""seals

Revision ID: cbcabbea8868
Revises: d0b97f4dbc42
Create Date: 2019-06-26 13:53:01.710090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcabbea8868'
down_revision = 'd0b97f4dbc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('seals', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'seals')
    # ### end Alembic commands ###
